### ISSUE TITLE
Make configuration more parametric

### ISSUE THREAD

**Issue by gabriele-decapoa** [gabriele-decapoa/nodejs-cloudant#2]
Find a way (using some NPM libraries) to make configuration files more parametric and more manageable.

**Comment by gabriele-decapoa** [comment]
Now the configuration is loaded by `nconf` library and read by `ConfigMap` and `Secret`, so it highly parametric.
This task is completed.

**Comment by dvesperini** [comment]
From my side in this days I studied Angular and a way to change our code in
order to use the new framework, when I have some news I will let you know.
:)

Il dom 12 ago 2018, 15:46 Gabriele de Capoa <notifications@github.com> ha
scritto:
